[package]
name = "lidar-ld19"
version = "0.2.2"
edition = "2021"
authors = ["12345qiupeng <>", "YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[dependencies]
serialport = { version = "4", default-features = false }
log = "*"
env_logger = "0.11"
minifb = "0.27"
